### ISSUE TITLE
Create Design, UI and UX for the entire website

### ISSUE THREAD

**Issue by jessieAnhNguyen** [jessieAnhNguyen/Grocery-Cache#1]
- Design the UI/UX theme
- Implement it on the landing page

**Comment by shrestha-aman** [comment]
Using these websites as references. Will post the most recent update soon.

https://www.thekitchn.com/outsmart-food-label-colors-while-you-shop-tips-from-the-kitchn-208689

https://www.sessions.edu/color-calculator/

**Comment by shrestha-aman** [comment]
Please don't hate on the colors, I used the websites mentioned above to choose orange cause apparently it will "satisfy the customers". I've attached screenshots in this comment and I have sent the video of how it could look like in the chat (cause I couldn't upload a video). I don't know how the budget part should look like so haven't done that yet. 
![image](https://user-images.githubusercontent.com/33694448/100047810-60366080-2de1-11eb-823c-fdf5cb443aa6.png)
![image](https://user-images.githubusercontent.com/33694448/100047829-6af0f580-2de1-11eb-8e89-7c6a1d857bc5.png)
![image](https://user-images.githubusercontent.com/33694448/100047839-70e6d680-2de1-11eb-932f-6abd94eacdab.png)
![image](https://user-images.githubusercontent.com/33694448/100047849-76dcb780-2de1-11eb-93b5-f7018254a8e7.png)
![image](https://user-images.githubusercontent.com/33694448/100047863-7cd29880-2de1-11eb-9820-68ccb18c6bb1.png)

**Comment by jessieAnhNguyen** [comment]
@amnshrestha This looks really dope and implementable 😎 I prefer breaking down the first image into 2 last images. What I mean is in our homepage, just list the items. Then in the categories page, list each category.
